---
- name: Install Dependencies
  hosts: localhost
  become: false
  vars:
    the_user: "{{ ansible_user_id }}"
    manager_packages:
      - cmake
      # - google-cloud-cli
      - helix  # TODO Needs extra setup in ubuntu - https://docs.helix-editor.com/install.html
      - hugo
      - kubectl
      - k9s
      - terraform
    cargo_packages:
      - bat
      - bacon
      - bob-nvim
      - bottom
      - cargo-info
      - coreutils
      - du-dust
      - exa
      - fd-find
      - fnm
      - gitui
      - irust
      - mprocs
      - nu
      - ripgrep
      - rtx-cli
      - speedtest-rs
      - starship
      - wiki-tui
      - zellij
      - zoxide
    pip_packages:
      - frogmouth
    config_dirs:
      - "/Users/{{ ansible_user_id }}/Library/Application Support/nushell"
      - "{{ ansible_env.HOME }}/.config/helix"
      - "{{ ansible_env.HOME }}/.config/alacritty"
      - "{{ ansible_env.HOME }}/.config/zellij"
    dotfiles:
      - src: "{{ playbook_dir }}/starship.toml"
        dest: "{{ ansible_env.HOME }}/.config/starship.toml"
      - src: "{{ playbook_dir }}/env.nu"
        dest: "/Users/{{ ansible_user_id }}/Library/Application Support/nushell/env.nu"
      - src: "{{ playbook_dir }}/config.nu"
        dest: "/Users/{{ ansible_user_id }}/Library/Application Support/nushell/config.nu"
      - src: "{{ playbook_dir }}/alacritty.yml"
        dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
      - src: "{{ playbook_dir }}/aliases.sh"
        dest: "{{ ansible_env.HOME }}/aliases.sh"
      - src: "{{ playbook_dir }}/helix-config.toml"
        dest: "{{ ansible_env.HOME }}/.config/helix/config.toml"
      - src: "{{ playbook_dir }}/helix-languages.toml"
        dest: "{{ ansible_env.HOME }}/.config/helix/languages.toml"
      - src: "{{ playbook_dir }}/zellij-config.kdl"
        dest: "{{ ansible_env.HOME }}/.config/zellij/config.kdl"
      - src: "{{ playbook_dir }}/zellij-layouts"
        dest: "{{ ansible_env.HOME }}/.config/zellij/layouts"

  tasks:
    - name: Install with package manager
      become: no
      ansible.builtin.package:
        name: "{{ item }}"
        state: latest
      register: result
      until: result is successful
      loop: "{{ manager_packages }}"

    - name: Check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes

    - name: Download cargo installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    - name: Install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust

    - name: Install sccache
      community.general.cargo:
        name: "sccache"
        path: "{{ ansible_env.HOME }}/.cargo"
        state: latest
      register: result
      until: result is successful
      tags:
        - rust

    - name: Install with cargo
      community.general.cargo:
        name: "{{ item }}"
        path: "{{ ansible_env.HOME }}/.cargo"
        state: latest
      register: result
      until: result is successful
      environment:
        RUSTC_WRAPPER: "{{ ansible_env.HOME }}/.cargo/bin/sccache"
      loop: "{{ cargo_packages }}"
      tags:
        - rust

    - name: Install with pip
      ansible.builtin.pip:
        name: "{{ item }}"
        executable: pip3
        state: latest
      register: result
      until: result is successful
      loop: "{{ pip_packages }}"

    - name: Change user shell to nu
      become: yes
      user: 
        name: "{{ the_user }}"
        shell: "{{ ansible_env.HOME }}/.cargo/bin/nu"

    - name: Create config directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      loop: "{{ config_dirs }}"
      tags:
        - dotfiles

    - name: Create symbolic links to the dotfiles
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop: "{{ dotfiles }}"
      tags:
        - dotfiles
