---
- name: Install Dependencies
  hosts: localhost
  become: false
  vars:
    the_user: "{{ ansible_user_id }}"
    manager_packages:
      - cmake
      - helix  # TODO Needs extra setup in ubuntu - https://docs.helix-editor.com/install.html
    cargo_packages:
      - bat
      - bacon
      - bob-nvim
      - bottom
      - cargo-info
      - coreutils
      - du-dust
      - exa
      - fd-find
      - gitui
      - irust
      - nu
      - ripgrep
      - rtx-cli
      - speedtest-rs
      - starship
      - wiki-tui
      - zellij
      - zoxide

  tasks:
    - name: Install with package manager
      become: yes
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      register: result
      until: result is successful
      loop: "{{ manager_packages }}"

    - name: Install sccache
      community.general.cargo:
        name: "sccache"
        path: "{{ ansible_env.HOME }}/.cargo"
        state: present
      register: result
      until: result is successful

    - name: Install with cargo
      community.general.cargo:
        name: "{{ item }}"
        path: "{{ ansible_env.HOME }}/.cargo"
        state: present 
      register: result
      until: result is successful
      environment:
        RUSTC_WRAPPER: "{{ ansible_env.HOME }}/.cargo/bin/sccache"
      loop: "{{ cargo_packages }}"

    - name: Change user shell to nu
      become: yes
      user: 
        name: "{{ the_user }}"
        shell: "{{ ansible_env.HOME }}/.cargo/bin/nu"
