[[language]]
name = "markdown"
scope = "text.markdown"
injection-regex = "markdown"
file-types = ["md"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"