theme = "github_dark_tritanopia"

[editor]
true-color = true
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
line-number = "relative"
soft-wrap.enable = true
# These are currently in master but not a release, so commenting for now
# # Trim whitespace preceding line endings on write (default false)
# trim-trailing-whitespace = true
# # Trim extra line endings after the final one on write (default false)
# trim-final-newlines = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.indent-guides]
render = true
character = "|"
skip-levels = 1

[editor.file-picker]
hidden = false
git-ignore = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
